package PDFService;


/**
* PDFService/ByteArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, April 29, 2026 10:21:27 AM GMT
*/

public final class ByteArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public ByteArrayHolder ()
  {
  }

  public ByteArrayHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.ByteArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.ByteArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.ByteArrayHelper.type ();
  }

}
