package PDFService;


/**
* PDFService/IPDFService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, April 29, 2026 10:21:27 AM GMT
*/

public interface IPDFService extends IPDFServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPDFService
