package PDFService;


/**
* PDFService/IPDFServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, April 29, 2026 10:21:27 AM GMT
*/

public abstract class IPDFServicePOA extends org.omg.PortableServer.Servant
 implements PDFService.IPDFServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("fusionnerPDF", new java.lang.Integer (0));
    _methods.put ("decouperPDF", new java.lang.Integer (1));
    _methods.put ("extrairePage", new java.lang.Integer (2));
    _methods.put ("supprimerPage", new java.lang.Integer (3));
    _methods.put ("ajouterMotDePasse", new java.lang.Integer (4));
    _methods.put ("convertirEnImage", new java.lang.Integer (5));
    _methods.put ("extraireTexte", new java.lang.Integer (6));
    _methods.put ("creerPDF", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Fusion de deux PDFs
       case 0:  // PDFService/IPDFService/fusionnerPDF
       {
         try {
           byte pdf1[] = PDFService.ByteArrayHelper.read (in);
           byte pdf2[] = PDFService.ByteArrayHelper.read (in);
           byte $result[] = null;
           $result = this.fusionnerPDF (pdf1, pdf2);
           out = $rh.createReply();
           PDFService.ByteArrayHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Découpage d'un PDF (page debut à page fin)
       case 1:  // PDFService/IPDFService/decouperPDF
       {
         try {
           byte pdf[] = PDFService.ByteArrayHelper.read (in);
           int debut = in.read_long ();
           int fin = in.read_long ();
           byte $result[] = null;
           $result = this.decouperPDF (pdf, debut, fin);
           out = $rh.createReply();
           PDFService.ByteArrayHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Extraction d'une page spécifique
       case 2:  // PDFService/IPDFService/extrairePage
       {
         try {
           byte pdf[] = PDFService.ByteArrayHelper.read (in);
           int numPage = in.read_long ();
           byte $result[] = null;
           $result = this.extrairePage (pdf, numPage);
           out = $rh.createReply();
           PDFService.ByteArrayHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Suppression d'une page
       case 3:  // PDFService/IPDFService/supprimerPage
       {
         try {
           byte pdf[] = PDFService.ByteArrayHelper.read (in);
           int numPage = in.read_long ();
           byte $result[] = null;
           $result = this.supprimerPage (pdf, numPage);
           out = $rh.createReply();
           PDFService.ByteArrayHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Ajout d'un mot de passe
       case 4:  // PDFService/IPDFService/ajouterMotDePasse
       {
         try {
           byte pdf[] = PDFService.ByteArrayHelper.read (in);
           String motDePasse = in.read_string ();
           byte $result[] = null;
           $result = this.ajouterMotDePasse (pdf, motDePasse);
           out = $rh.createReply();
           PDFService.ByteArrayHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Conversion d'une page PDF en image PNG
       case 5:  // PDFService/IPDFService/convertirEnImage
       {
         try {
           byte pdf[] = PDFService.ByteArrayHelper.read (in);
           int numPage = in.read_long ();
           byte $result[] = null;
           $result = this.convertirEnImage (pdf, numPage);
           out = $rh.createReply();
           PDFService.ByteArrayHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Extraction du texte d'un PDF
       case 6:  // PDFService/IPDFService/extraireTexte
       {
         try {
           byte pdf[] = PDFService.ByteArrayHelper.read (in);
           String $result = null;
           $result = this.extraireTexte (pdf);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Création d'un PDF depuis un texte
       case 7:  // PDFService/IPDFService/creerPDF
       {
         try {
           String contenu = in.read_string ();
           byte $result[] = null;
           $result = this.creerPDF (contenu);
           out = $rh.createReply();
           PDFService.ByteArrayHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFService/IPDFService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IPDFService _this() 
  {
    return IPDFServiceHelper.narrow(
    super._this_object());
  }

  public IPDFService _this(org.omg.CORBA.ORB orb) 
  {
    return IPDFServiceHelper.narrow(
    super._this_object(orb));
  }


} // class IPDFServicePOA
